### PR TITLE
Answer screen monik

### PR DESCRIPTION
**Pull request by Monik09**
Issue: 5
#5 
#### Short description of what this resolves:
Creates basic Figma layout of the Answer screen.

#### Changes proposed in this pull request and/or Screenshots of changes:

https://user-images.githubusercontent.com/52850691/135828880-f6ab8500-8de2-4e6a-af63-5107046f20b1.mp4

### CODE REVIEW

**Review by cyber-venom003 — COMMENTED** [review]
@Monik09 Resolve the Merge conflicts. 
Otherwise it is perfectly implemented.

**Comment by Sam-commit** [comment]
Please resolve the merge conflicts

**Comment by Monik09** [comment]
@cyber-venom003 @Sam-commit I have resolved the conflict.

**Comment by Sam-commit** [comment]
@Monik09 nice work buddy

**Pull request merged**
