### PR TITLE
Moved fonts to root of fonts directory

### LINKED ISSUE #11: Refactoring Fonts folder
In the fonts folder, put all the files directly under fonts folder instead of static folder as it might give error while compiling.

### PR DESCRIPTION
**Pull request by criticic**
Issue: 11

#### Short description of what this resolves:
Moved fonts out of static directory.

Closes #11

### CODE REVIEW

**Comment by criticic** [comment]
@Sam-commit Please take a look.

**Comment by Sam-commit** [comment]
> @Sam-commit Please take a look.

please upload a screenshot of running app on emulator, so that we know fonts are still working

**Comment by Monik09** [comment]
> > @Sam-commit Please take a look.
> 
> please upload a screenshot of running app on emulator, so that we know fonts are still working

There was some issues with the font files and I have solved them in my PR for bottom navigation bar because without solving that issue, it was not possible to run app.

**Comment by criticic** [comment]
> > > @Sam-commit Please take a look.
> > 
> > 
> > please upload a screenshot of running app on emulator, so that we know fonts are still working
> 
> There was some issues with the font files and I have solved them in my PR(#14) for bottom navigation bar because without solving that issue, it was not possible to run app.

Once this is implemented, that issue might not be there.
For testing, please revert the publock.yaml to original state after moving the fonts out of static.
> > @Sam-commit Please take a look.
> 
> please upload a screenshot of running app on emulator, so that we know fonts are still working
i cannot do that sadly, my pc is not good enough(does not have hardware virtualisation capability). i looked into the project, and the only reference to the fonts was in publock.yaml. So i believe it would work.

**Comment by Monik09** [comment]
> > There was some issues with the font files and I have solved them in my PR(#14) for bottom navigation bar because without solving that issue, it was not possible to run app.
> 
> Once this is implemented, that issue might not be there. For testing, please revert the publock.yaml to original state after moving the fonts out of static.
> 
> > please upload a screenshot of running app on emulator, so that we know fonts are still working
> 
> i cannot do that sadly, my pc is not good enough(does not have hardware virtualisation capability). i looked into the project, and the only reference to the fonts was in publock.yaml. So i believe it would work.

oh ok. Actually, in my PR I just changed the path in pubspec.yaml(adding the static variable in between).

**Comment by criticic** [comment]
@Sam-commit considering #14 was merged, and it was succesfully working, is this PR required?

**Comment by Monik09** [comment]
@criticic I didn't move the fonts out of the static folder in PR#14 and you wanted to move the fonts out of the static folder. So if that issue was accepted I think you can still make PR but you will need to change the font path.

**Comment by Sam-commit** [comment]
> @Sam-commit considering #14 was merged, and it was successfully working, is this PR required?

yes you are right, there is no need for this issue after PR 14 but moving fonts out of static will work too so its fine no problem there.

**Pull request merged**
